export enum AppRoute {
	Home = '/',
	Search = 'search',
	About = 'about',
	AboutHistory = 'about-history',
	AboutNature = 'about-nature',
	AboutCulture = 'about-culture',
	AboutTraditions = 'about-traditions',
	AboutGames = 'about-games',
	AboutContacts = 'about-contacts',
	Objects = 'objects-list',
	News = 'news',
	Videos = 'videos',
	Events = 'events',
	EventMaps = 'event-maps',
	EventParticipants = 'event-participants',
	EventTeams = 'event-teams',
}
